### ISSUE TITLE
Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Mhhhaster** [gen-ko/lanms-neo#3]
when I tried: pip install lanms-neo
and then get:

/tmp/pip-build-env-zjv64fgc/overlay/lib/python3.6/site-packages/pybind11/include/pybind11/detail/../detail/common.h:266:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for lanms-neo
Failed to build lanms-neo
ERROR: Could not build wheels for lanms-neo, which is required to install pyproject.toml-based projects.

OS : centos

**Comment by yuanliu939** [comment]
Check your gcc installation.

**Comment by nissansz** [comment]
creating build\temp.win-amd64-cpython-38
      creating build\temp.win-amd64-cpython-38\Release
      creating build\temp.win-amd64-cpython-38\Release\src
      cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DDEFAULT_STYLE=STYLE_LIST -DSYSTEM_WIN32=1 -Isrc -ID:\Python3.8.8\include -ID:\Python3.8.8\Include /Tcsrc/PolyUtil.c /Fobuild\temp.win-amd64-cpython-38\Release\src/PolyUtil.obj
      PolyUtil.c
      c:\users\ni\appdata\local\temp\pip-install-thbjo96r\polygon3_eeec1aada977483689fcd882bbfc72c5\src\gpc.h(36): fatal error C1083: 无法打开包括文件: “stdio.h”: No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Polygon3
Failed to build Polygon3
ERROR: Could not build wheels for Polygon3, which is required to install pyproject.toml-based projects
